apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "adservice.name" . }}
  labels:
    {{- include "adservice.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "adservice.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "adservice.selectorLabels" . | nindent 8 }}
    spec:
      # {{- with .Values.imagePullSecrets }}
      # imagePullSecrets:
      #   {{- toYaml . | nindent 8 }}
      # {{- end }}
      serviceAccountName: {{ include "adservice.serviceAccountName" . }}
      terminationGracePeriodSeconds: {{ .Values.tgps}}
      containers:
        - name: {{ .Values.containername }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
              containerPort: 9555
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:9555"]
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:9555"]
          resources:
            requests:
                cpu: {{- .Values.resources.requests.cpu}}
                memory: {{- .Values.resources.requests.memory}}

            limits:
                cpu: {{- .Values.resources.limits.cpu}}
                memory: {{- .Values.resources.limits.memory}}      
